# -*- coding: utf-8 -*-
"""CaptchaPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAOkDNzX1mL9y1tf_105js0m7R5T_fG6
"""

from captcha.image import ImageCaptcha
import random
import string
from PIL import Image
from IPython.display import display

# Membuat objek ImageCaptcha
image = ImageCaptcha(width=280, height=90)

# Membuat teks CAPTCHA secara acak
def generate_random_text(length=5):
    letters = string.ascii_uppercase + string.digits
    return ''.join(random.choice(letters) for _ in range(length))

captcha_text = generate_random_text()

# Membuat gambar CAPTCHA dengan teks yang dihasilkan
image.write(captcha_text, 'captcha.png')

print(f"CAPTCHA text is: {captcha_text}")

# Membuka dan menampilkan gambar CAPTCHA di Colab
img = Image.open('captcha.png')
display(img)

# Verifikasi Captcha
# Meminta input dari pengguna untuk verifikasi
user_input = input("Please enter the CAPTCHA text: ")

if user_input == captcha_text:
    print("CAPTCHA verification passed.")
else:
    print("CAPTCHA verification failed.")