# -*- coding: utf-8 -*-
"""Fernando_LinkedList_41523010038.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TrwSobOWtbfqpFM-xtuya8J-_aCY0n5O
"""

class Node:
  def __init__(self,data):
     self.data = data
     self.next = None

class Linkedlist:
  def __init__(self):
     self.head = None

  def InsertAtBeginning(self,newdata):
     new_node = Node(newdata)
     new_node.next = self.head
     self.head = new_node

  def printList(self):
     temp = self.head
     while temp:
        print(temp.data,end=' ')
        temp = temp.next
     print()

  def deleteFromBeginning(self):
     if self.head is None:
       return "The List is empty"
     self.head = self.head.next

  def deleteFromEnd(self):
    if self.head is None:
      return "The List is empty"
    if self.head.next is None:
      self.head = None
      return
    temp = self.head
    while temp.next.next:
      temp = temp.next
    temp.next = None
    
  def deleteAll (self):
     for i in range (0,2):
      self.head = self.head.next

  def search (self,value):
    current = self.head
    position = 0
    while current:
      if current.data == value:
        return f"Value {value} found at Position {position}"
      current = current.next
      position += 1
    return f"Value {value} not found in the list"




if __name__ == '__main__':
  llist = Linkedlist()
  llist.InsertAtBeginning('Fox')
  llist.InsertAtBeginning('Brown')
  llist.InsertAtBeginning('Quick')
  llist.InsertAtBeginning('The')

  # Print list sebelum dihapus
  print("List Before Deletion: ")
  llist.printList()

Ask = input("Apakah data Anda mau delete Y/T: ")

# Membuat Kondisi
# Kondisi jika inputan memilih y/Y
if (Ask == "y" or Ask == "Y"):
   # Menghapus awal linkedlist
   llist.deleteFromBeginning()
   print("List After Deletion (Beginning):")
   llist.printList()

   # Menghapus akhir linkedlist
   llist.deleteFromEnd()
   print("List After Deletion (End):")
   llist.printList()

   # Mencari data
   print(llist.search('Quick'))
   print(llist.search('lazy'))

   # Menghapus keseluruhan linkedlist
   llist.deleteAll()
   print("List After Deletion (All):")
   llist.printList()

# kondisi jika inputan memilih t/T
elif (Ask == "t" or Ask == "T"):
  print("List Not Deletion")
  llist.printList()
# kondisi jika inputan bukan y maupun t
else:
  print("Input tidak ditemukan. Silakan masukkan input yang benar.")